version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci
  pre_build:
    commands:
      - echo "Verifying environment variables..."
      - echo "VITE_USER_POOL_ID=$VITE_USER_POOL_ID"
      - echo "VITE_USER_POOL_CLIENT_ID=$VITE_USER_POOL_CLIENT_ID"
      - echo "VITE_COGNITO_DOMAIN=$VITE_COGNITO_DOMAIN"
      - echo "VITE_API_ENDPOINT=$VITE_API_ENDPOINT"
      - echo "Environment variables verified. Vite will use them directly."
  build:
    commands:
      - echo "Building the Vuetify application..."
      - npm run build-only
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Dist folder prepared for S3 deployment"
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
