/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiGatewaySetting: typeof import('./components/info/ApiGatewaySetting.vue')['default']
    AzSetting: typeof import('./components/info/AzSetting.vue')['default']
    BaseSetting: typeof import('./components/info/BaseSetting.vue')['default']
    CloudFrontSetting: typeof import('./components/info/CloudFrontSetting.vue')['default']
    ComputeSetting: typeof import('./components/info/ComputeSetting.vue')['default']
    CostExplorerDialog: typeof import('./components/utils/CostExplorerDialog.vue')['default']
    ElasticIpSetting: typeof import('./components/info/ElasticIpSetting.vue')['default']
    EndpointSetting: typeof import('./components/info/EndpointSetting.vue')['default']
    FargateSetting: typeof import('./components/info/FargateSetting.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InfoTab: typeof import('./components/info/InfoTab.vue')['default']
    Layer: typeof import('./components/layer/Layer.vue')['default']
    LayerAddButton: typeof import('./components/layer/LayerAddButton.vue')['default']
    LayerTab: typeof import('./components/layer/LayerTab.vue')['default']
    LoadBalancerSetting: typeof import('./components/info/LoadBalancerSetting.vue')['default']
    MensCoachDialog: typeof import('./components/utils/MensCoachDialog.vue')['default']
    NatGatewaySetting: typeof import('./components/info/NatGatewaySetting.vue')['default']
    PlayBoard: typeof import('./components/board/PlayBoard.vue')['default']
    RdsSetting: typeof import('./components/info/RdsSetting.vue')['default']
    Route53Setting: typeof import('./components/info/Route53Setting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./components/Service.vue')['default']
    ServiceIcon: typeof import('./components/board/ServiceIcon.vue')['default']
    ServiceItem: typeof import('./components/layer/ServiceItem.vue')['default']
    ServicesTab: typeof import('./components/ServicesTab.vue')['default']
    Shape: typeof import('./components/Shape.vue')['default']
    SubnetContainer: typeof import('./components/board/SubnetContainer.vue')['default']
    SubnetSetting: typeof import('./components/info/SubnetSetting.vue')['default']
    VpcContainer: typeof import('./components/board/VpcContainer.vue')['default']
    VpcSetting: typeof import('./components/info/VpcSetting.vue')['default']
  }
}
