/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseSetting: typeof import('./components/info/BaseSetting.vue')['default']
    ComputeSetting: typeof import('./components/info/ComputeSetting.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InfoTab: typeof import('./components/info/InfoTab.vue')['default']
    Layer: typeof import('./components/layer/Layer.vue')['default']
    LayerAddButton: typeof import('./components/layer/LayerAddButton.vue')['default']
    LayerTab: typeof import('./components/layer/LayerTab.vue')['default']
    PlayBoard: typeof import('./components/board/PlayBoard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./components/Service.vue')['default']
    ServiceItem: typeof import('./components/layer/ServiceItem.vue')['default']
    ServicesTab: typeof import('./components/ServicesTab.vue')['default']
    Shape: typeof import('./components/Shape.vue')['default']
    VpcSetting: typeof import('./components/info/VpcSetting.vue')['default']
  }
}
